// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by builder.dart at 2025-10-02 23:01:52.708155

/// Annotation to generate toString method for a class
class GenerateToString {
  const GenerateToString();
}

/// Annotation to generate equality (== and hashCode) methods for a class
class GenerateEquality {
  const GenerateEquality();
}

/// Annotation to generate JSON serialization methods
class JsonSerializable {
  final bool explicitToJson;
  final bool includeIfNull;

  const JsonSerializable({
    this.explicitToJson = false,
    this.includeIfNull = true,
  });
}

/// Annotation to generate a copyWith method for a class
class GenerateCopyWith {
  const GenerateCopyWith();
}

/// Annotation to mark a class for inclusion in builderInitializer
class Initializer {
  const Initializer();
}

// Convenience constants for common use
const generateToString = GenerateToString();
const generateEquality = GenerateEquality();
const jsonSerializable = JsonSerializable();
const generateCopyWith = GenerateCopyWith();
const initializer = Initializer();
