// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by builder.dart at 2025-10-06 21:52:45.770286

/// Annotation to generate a copyWith method for a class
class GenerateCopyWith {
  const GenerateCopyWith();
}

/// Annotation to generate equality (== and hashCode) methods for a class
class GenerateEquality {
  const GenerateEquality();
}

/// Annotation to mark a class for inclusion in builderInitializer
class Initializer {
  const Initializer();
}

/// Annotation to generate JSON serialization methods
class JsonSerializable {
  final bool explicitToJson;
  final bool includeIfNull;

  const JsonSerializable({
    this.explicitToJson = false,
    this.includeIfNull = true,
  });
}

/// Annotation to generate toString method for a class
class GenerateToString {
  const GenerateToString();
}

// Convenience constants for common use
const generateCopyWith = GenerateCopyWith();
const generateEquality = GenerateEquality();
const initializer = Initializer();
const jsonSerializable = JsonSerializable();
const generateToString = GenerateToString();
