// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by builder.dart at 2025-10-11 22:16:00.014594

class GenerateCopyWith {
  /// Annotation to generate a copyWith method for a class
  const GenerateCopyWith();
}

class GenerateEquality {
  /// Annotation to generate equality (== and hashCode) methods for a class
  ///
  /// Add these methods to the class
  /// ```
  /// @override
  /// bool operator ==(Object other) => isEqualTo(other);
  /// @override
  /// int get hashCode => generatedHashCode;
  /// ```
  const GenerateEquality();
}

class Initializer {
  /// Annotation to mark a class for inclusion in builderInitializer
  const Initializer();
}

/// Annotation to generate JSON serialization methods
class JsonSerializable {
  final bool explicitToJson;
  final bool includeIfNull;

  /// Annotation to generate JSON serialization methods
  const JsonSerializable({
    this.explicitToJson = false,
    this.includeIfNull = true,
  });
}

class GenerateToString {
  /// Annotation to generate toString method for a class
  ///
  /// Add this method to the class
  /// ```
  /// @override
  /// String toString() => toStringGenerated();
  /// ```
  const GenerateToString();
}

// Convenience constants for common use
/// Annotation to generate a copyWith method for a class
const generateCopyWith = GenerateCopyWith();

/// Annotation to generate equality (== and hashCode) methods for a class
///
/// Add these methods to the class
/// ```
/// @override
/// bool operator ==(Object other) => isEqualTo(other);
/// @override
/// int get hashCode => generatedHashCode;
/// ```
const generateEquality = GenerateEquality();

/// Annotation to mark a class for inclusion in builderInitializer
const initializer = Initializer();

/// Annotation to generate JSON serialization methods
const jsonSerializable = JsonSerializable();

/// Annotation to generate toString method for a class
///
/// Add this method to the class
/// ```
/// @override
/// String toString() => toStringGenerated();
/// ```
const generateToString = GenerateToString();
