// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by builder.dart at 2025-10-06 22:14:22.512042

// ignore_for_file: unused_import
import 'annotations/copyWith_annotation.dart';
import 'annotations/equality_annotation.dart';
import 'annotations/initializer_annotation.dart';
import 'annotations/json_annotation.dart';
import 'annotations/toString_annotation.dart';

/// Global initializer function that calls all initialize() methods
/// and executes their optional callbacks after initialization
void builderInitializer() {
  final callbacks = <Function()>[];

  // Call all initialize methods and collect callbacks
  final copywithannotationCallback = CopyWithAnnotation.initialize();
  if (copywithannotationCallback != null)
    callbacks.add(copywithannotationCallback);

  final equalityannotationCallback = EqualityAnnotation.initialize();
  if (equalityannotationCallback != null)
    callbacks.add(equalityannotationCallback);

  final initializerannotationCallback = InitializerAnnotation.initialize();
  if (initializerannotationCallback != null)
    callbacks.add(initializerannotationCallback);

  final jsonannotationCallback = JsonAnnotation.initialize();
  if (jsonannotationCallback != null) callbacks.add(jsonannotationCallback);

  final tostringannotationCallback = ToStringAnnotation.initialize();
  if (tostringannotationCallback != null)
    callbacks.add(tostringannotationCallback);

  // Execute all callbacks after initialization
  for (final callback in callbacks) {
    callback();
  }
}
