name: builder
description: Custom code generator for flutter_annotations

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.1.1
  dart_style: ^3.1.2
  path: ^1.9.1
  args: ^2.7.0
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
